import React from 'react';
import { Code } from 'lucide-react';

export const CodeBlock = () => (
  <div className="bg-slate-900 rounded-lg overflow-hidden my-4 border border-slate-700">
    <div className="bg-slate-800 px-3 py-2 flex justify-between items-center border-b border-slate-700">
      <span className="text-xs text-slate-300 flex items-center gap-2">
        <Code size={12} className="text-green-400"/> Generated Python (PyTorch)
      </span>
      <span className="text-[10px] text-slate-500">v1.0 generated by Agent</span>
    </div>
    <div className="p-3 overflow-x-auto">
      <pre className="text-xs font-mono text-green-300 leading-relaxed">
{`class Attention(nn.Module):
    def forward(self, Q, K, V):
        # Implementation of Eq(1)
        scores = torch.matmul(Q, K.transpose(-2, -1))
        scores = scores / math.sqrt(d_k)
        attn = F.softmax(scores, dim=-1)
        return torch.matmul(attn, V)`}
      </pre>
    </div>
    <div className="bg-slate-800/50 px-3 py-1.5 flex justify-end">
      <button className="text-[10px] text-white bg-green-600 px-2 py-0.5 rounded hover:bg-green-500">Copy Code</button>
    </div>
  </div>
);